export DATASET="fardet-vd:fardet-vd__full-reconstructed__v09_81_00d02__reco2_dunevd10kt_nu_1x8x6_3view_30deg_geov3__prodgenie_nu_dunevd10kt_1x8x6_3view_30deg__out1__v2_official"
export FCL=cafmaker_atmos_dune10kt_1x2x6_runreco-nuenergy-nuangular_geov5.fcl
export MERGE_VERSION=$DUNESW_VERSION
export DETECTOR=fardet-vd
export CHUNK=2
export SKIP=0
export RUN=0
export NFILES=10
export FILETYPE="mc"
export MERGE_VERSION=v09_91_02d01
export DESTINATION=local
export TIMESTAMP=date
export USERNAME=$USER
export USELAR
export LARCONFIG=${FCL}
export _CONDOR_SCRATCH_DIR=$PWD
export INPUT_TAR_DIR_LOCAL=$PWD
source remote_lar.sh