source  examples/MergeLar_hd.sh >& examples/MergeLar_hd.sh.log &
source  examples/MergeTar.sh >& examples/MergeTar.sh.log &
#source  examples/TarSmall.sh >& examples/TarSmall.sh.log &
source  examples/interactiveDirectParentage.sh >& examples/interactiveDirectParentage.sh.log &
source  examples/interactiveMerge.sh >& examples/interactiveMerge.sh.log &
source  examples/interactiveRun.sh >& examples/interactiveRun.sh.log &
#source  examples/makeCAF.sh >& examples/makeCAF.sh.log &
#source  examples/makeList.sh >& examples/makeList.sh.log &
source  examples/submitLar.sh >& examples/submitLar.sh.log &
source  examples/submitRun.sh >& examples/submitRun.sh.log &
#source  examples/subonly.sh >& examples/subonly.sh.log &
#source  examples/subsetup.sh >& examples/subsetup.sh.log &
#source  examples/testBatch.sh >& examples/testBatch.sh.log &
source  examples/testBatchSuite.sh >& examples/testBatchSuite.sh.log &
