source  MergeLar.sh > MergeLar.sh.log
source  MergeTar.sh > MergeTar.sh.log
source  TarSmall.sh > TarSmall.sh.log
source  clean.sh > clean.sh.log
source  interactiveDirectParentage.sh > interactiveDirectParentage.sh.log
source  interactiveMerge.sh > interactiveMerge.sh.log
source  interactiveRun.sh > interactiveRun.sh.log
source  makeCAF.sh > makeCAF.sh.log
source  makeList.sh > makeList.sh.log
source  submitLar.sh > submitLar.sh.log
source  submitRun.sh > submitRun.sh.log
source  subonly.sh > subonly.sh.log
source  subsetup.sh > subsetup.sh.log
source  testBatch.sh > testBatch.sh.log
source  testBatchSuite.sh > testBatchSuite.sh.log
